apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: RAMShare
metadata:
  name: ipam-pools-shared
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: aws-management
    kind: ProviderConfig

  region: us-east-1
  name: ipam-pools-platform

  # Organization-only sharing (no external accounts)
  allowExternalPrincipals: false

  # Resources to share
  resources:
    - name: ipv4-us-east-1
      arn: arn:aws:ec2::123456789012:ipam-pool/ipam-pool-0abc123def456789a
    - name: ipv4-us-west-2
      arn: arn:aws:ec2::123456789012:ipam-pool/ipam-pool-0def456abc789012b

  # Share with Teams OU
  principals:
    - name: teams-ou
      type: organizationalUnit
      arn: arn:aws:organizations::123456789012:ou/o-abc123def4/ou-root-teams

  tags:
    environment: platform
    purpose: ipam-sharing
