apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: RAMShare
metadata:
  name: internal-pki
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: aws-security
    kind: ProviderConfig

  region: us-east-1
  name: internal-certificate-authority

  allowExternalPrincipals: false

  # Share the Private CA
  resources:
    - name: root-ca
      arn: arn:aws:acm-pca:us-east-1:333333333333:certificate-authority/abc123-def456-789012

  # Share with entire organization
  principals:
    - name: entire-org
      type: organization
      arn: arn:aws:organizations::111111111111:organization/o-abc123def4

  tags:
    environment: security
    purpose: internal-pki
